version: '3.8'
services:
  forum:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./forum.db:/app/forum.db
      - ./static:/app/static
      - ./templates:/app/templates
    restart: unless-stopped